# Generated by Django 3.1.5 on 2021-02-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_informe_id', models.CharField(blank=True, max_length=256, verbose_name='ID carpeta Informes')),
                ('folder_relevamiento_id', models.CharField(blank=True, max_length=256, verbose_name='ID carpeta relevamientos')),
                ('sheet_id', models.CharField(blank=True, max_length=256, verbose_name='ID planilla gestion')),
                ('remito_col', models.CharField(blank=True, max_length=256, verbose_name='Numero de columna remito')),
                ('informe_col', models.CharField(blank=True, max_length=256, verbose_name='Numero de columna informe')),
                ('relevamientos_col', models.CharField(blank=True, max_length=256, verbose_name='Numero de columna relevamientos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
