# Generated by Django 3.1.5 on 2021-02-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_informe_id', models.CharField(blank=True, max_length=256, verbose_name='ID carpeta Informes')),
                ('folder_relevamiento_id', models.CharField(blank=True, max_length=256, verbose_name='ID carpeta relevamientos')),
                ('sheet_id', models.CharField(blank=True, max_length=256, verbose_name='ID planilla gestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
