# Generated by Django 3.1.5 on 2021-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='informe_col',
            field=models.CharField(blank=True, max_length=256, verbose_name='Numero de columna informe'),
        ),
        migrations.AddField(
            model_name='config',
            name='relevamientos_col',
            field=models.CharField(blank=True, max_length=256, verbose_name='Numero de columna relevamientos'),
        ),
        migrations.AddField(
            model_name='config',
            name='remito_col',
            field=models.CharField(blank=True, max_length=256, verbose_name='Numero de columna remito'),
        ),
    ]
